# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MeenyApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # react-native-config: .env 변수를 xcconfig에 주입
    installer.aggregate_targets.each do |target|
      target.xcconfigs.each do |config_name, config_file|
        rn_config = '../node_modules/react-native-config/ios/ReactNativeConfig.xcconfig'
        config_file.includes << rn_config unless config_file.includes.include?(rn_config)
        config_file.save_as(target.xcconfig_path(config_name))
      end
    end
  end
end
